name: uts_ambar
description: A new Flutter project for UTS Pemrograman Mobile.
publish_to: 'none'

environment:
  sdk: '^3.9.0'

dependencies:
  flutter:
    sdk: flutter

  # Format tanggal
  intl: ^0.19.0

  # Ikon iOS-style
  cupertino_icons: ^1.0.8

  # Navigasi bawah melengkung
  curved_navigation_bar: ^1.0.3

  # HTTP request
  http: ^1.2.0

  # Paket untuk kalkulator (tambahkan ini)
  math_expressions: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/profile.jpg
    - assets/cuaca.png
    - assets/berita1.jpg
    - assets/berita2.jpg
    - assets/berita3.jpg
    - assets/berita4.jpg
    - assets/profile1.jpg
    - assets/profile2.jpg
    - assets/profile3.jpg
    - assets/profile4.jpg
    - assets/profile5.jpg
    - assets/profile6.jpg
    - assets/profile7.jpg
    - assets/profile8.jpg
    - assets/profile9.jpg
    - assets/profile10.jpg
    - assets/profile11.jpg
    - assets/profile12.jpg
    - assets/profile13.jpg
    - assets/profile14.jpg
